###
# @name /signup
POST http://localhost:3009/auth/signup
Content-Type: application/json

{
  "email": "you@you.you",
  "password": "yourPa$$W0rd"
}

###
# @name /signin
POST http://localhost:3009/auth/signin
Content-Type: application/json

{
  "email": "you@you.you",
  "password": "yourPa$$W0rd"
}

###
# @name /signin
POST http://localhost:3009/auth/signin
Content-Type: application/json

{
  "email": "me@me.me",
  "password": "p@$$"
}

###
# @name /whoam
GET http://localhost:3009/auth/whoam

###
# @name /signout
POST http://localhost:3009/auth/signout

###
# @name /bad
POST http://localhost:3009/auth/signup
Content-Type: application/json

{
  "email": "https://not.email.nz",
  "password": 47
}

### get user by id
GET http://localhost:3009/auth/2

### get user by email
GET http://localhost:3009/auth?email=me@me.me

###
PATCH http://localhost:3009/auth/2
Content-Type: application/json

{
  "password": "pa$$word"
}

### remove a user
DELETE http://localhost:3009/auth/11
